name:  "GivTCP"
description:  "TCP Modbus connection to MQTT/JSON for Givenergy Battery/PV Invertors"
version:  "2.1.0"
image: britkat/giv_tcp-ma
slug:  "givtcp"
init:  true
map:
  - config:rw
boot:  auto
url:  https://github.com/britkat1980/giv_tcp
legacy:  true
arch: 
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
options:
  NUMINVERTORS: 1
  INVERTOR_IP_1:  ""
  NUMBATTERIES_1:  1
  MQTT_OUTPUT: True
  MQTT_ADDRESS: "core-mosquitto"
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  MQTT_TOPIC: ""
  MQTT_PORT: 1883
  LOG_LEVEL: "Error"
  PRINT_RAW: True
  SELF_RUN: True
  SELF_RUN_LOOP_TIMER: 5
  INFLUX_OUTPUT: False
  INFLUX_URL: ""
  INFLUX_TOKEN: ""
  INFLUX_BUCKET: ""
  INFLUX_ORG: ""
  HA_AUTO_D: True
  HADEVICEPREFIX: "GivTCP"
  PYTHONPATH: "/app"
  DAYRATE: "0.155"
  NIGHTRATE: "0.055"
  EXPORTRATE: "0.04"
  HOSTIP: "homeassistant.local"
  DAYRATESTART: "04:30"
  NIGHTRATESTART: "00:30"
  TZ: "Europe/London"
  WEB_DASH: False
  WEB_DASH_PORT: 3000
  INVERTOR_IP_2:  ""
  NUMBATTERIES_2:  1
  INVERTOR_IP_3:  ""
  NUMBATTERIES_3:  1
  CACHELOCATION: "/config/GivTCP"
  DATASMOOTHER: "High"
  SMARTTARGET: True
  GEAPI: ""
  SOLCASTAPI: ""
  SOLCASTSITEID: ""
schema: 
  NUMINVERTORS: int
  INVERTOR_IP_1:  str
  NUMBATTERIES_1:  int
  MQTT_OUTPUT: bool
  MQTT_ADDRESS: str
  MQTT_USERNAME: "str?"
  MQTT_PASSWORD: "str?"
  MQTT_TOPIC: "str?"
  MQTT_PORT: int
  LOG_LEVEL: str
  PRINT_RAW: bool
  SELF_RUN: bool
  SELF_RUN_LOOP_TIMER: int
  INFLUX_OUTPUT: bool
  INFLUX_URL: "str?"
  INFLUX_TOKEN: "str?"
  INFLUX_BUCKET: "str?"
  INFLUX_ORG: "str?"
  HA_AUTO_D: bool
  HADEVICEPREFIX: "str?"
  PYTHONPATH: str
  DAYRATE: "str?"
  NIGHTRATE: "str?"
  EXPORTRATE: "str?"
  HOSTIP: str
  DAYRATESTART: "str?"
  NIGHTRATESTART: "str?"
  TZ: str
  WEB_DASH: bool
  WEB_DASH_PORT: int
  INVERTOR_IP_2:  "str?"
  NUMBATTERIES_2:  "int?"
  INVERTOR_IP_3:  "str?"
  NUMBATTERIES_3:  "int?"
  CACHELOCATION: "str?"
  DATASMOOTHER: "str?"
  SMARTTARGET: bool
  GEAPI: "str?"
  SOLCASTAPI: "str?"
  SOLCASTSITEID: "str?"