name:  "GivTCP"
description:  "TCP Modbus connection to MQTT/JSON for Givenergy Battery/PV Invertors"
version:  "2.2.1"
image: britkat/giv_tcp-ma
slug:  "givtcp"
homeassistant_api: true
hassio_api: true
init:  true
services:
  - "mqtt:want"
map:
  - config:rw
boot:  auto
url:  https://github.com/britkat1980/giv_tcp
legacy:  true
arch: 
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
options:
  NUMINVERTORS: 1
  INVERTOR_IP_1:  ""
  INVERTOR_AIO_1: False
  NUMBATTERIES_1:  1
  HADEVICEPREFIX: "GivTCP"
  INVERTOR_IP_2:  ""
  NUMBATTERIES_2:  1
  INVERTOR_AIO_2: False
  HADEVICEPREFIX_2: "GivTCP2"
  INVERTOR_IP_3:  ""
  NUMBATTERIES_3:  1
  INVERTOR_AIO_3: False
  HADEVICEPREFIX_3: "GivTCP3"
  MQTT_OUTPUT: True
  MQTT_ADDRESS: "core-mosquitto"
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  MQTT_TOPIC: ""
  MQTT_TOPIC_2: ""
  MQTT_TOPIC_3: ""
  MQTT_PORT: 1883
  LOG_LEVEL: "Info"
  PRINT_RAW: True
  SELF_RUN: True
  SELF_RUN_LOOP_TIMER: 15
  QUEUE_RETRIES: 2
  HA_AUTO_D: True
  DYNAMICTARIFF: False
  DAYRATE: "0.155"
  NIGHTRATE: "0.055"
  EXPORTRATE: "0.04"
  DAYRATESTART: "04:30"
  NIGHTRATESTART: "00:30"
  INFLUX_OUTPUT: False
  INFLUX_URL: ""
  INFLUX_TOKEN: ""
  INFLUX_BUCKET: ""
  INFLUX_ORG: ""
  PYTHONPATH: "/app"  
  TZ: "Europe/London"
  WEB_DASH: False
  WEB_DASH_PORT: 3000
  HOSTIP: "homeassistant.local"
  CACHELOCATION: "/config/GivTCP"
  DATASMOOTHER: "medium"
  SMARTTARGET: False
  PALM_WINTER: "01,02,11,12"
  PALM_SHOULDER: "03,04,09,10"
  PALM_MIN_SOC_TARGET: 25
  PALM_MAX_SOC_TARGET: 45
  PALM_BATT_RESERVE: 4
  PALM_BATT_UTILISATION: 0.85
  PALM_WEIGHT: 35
  GEAPI: ""
  SOLCASTAPI: ""
  SOLCASTSITEID: ""
  SOLCASTSITEID2: ""
schema: 
  NUMINVERTORS: int
  INVERTOR_IP_1:  str
  NUMBATTERIES_1:  int
  INVERTOR_AIO_1: bool
  HADEVICEPREFIX: "str?"
  INVERTOR_IP_2:  "str?"
  NUMBATTERIES_2:  "int?"
  INVERTOR_AIO_2: bool
  HADEVICEPREFIX_2: "str?"
  INVERTOR_IP_3:  "str?"
  NUMBATTERIES_3:  "int?"
  INVERTOR_AIO_3: bool
  HADEVICEPREFIX_3: "str?"
  MQTT_OUTPUT: bool
  MQTT_ADDRESS: str
  MQTT_USERNAME: "str?"
  MQTT_PASSWORD: "str?"
  MQTT_TOPIC: "str?"
  MQTT_TOPIC_2: "str?"
  MQTT_TOPIC_3: "str?"
  MQTT_PORT: int
  LOG_LEVEL: str
  PRINT_RAW: bool
  SELF_RUN: bool
  SELF_RUN_LOOP_TIMER: int
  QUEUE_RETRIES: int
  HA_AUTO_D: bool
  DYNAMICTARIFF: bool
  DAYRATE: "str?"
  NIGHTRATE: "str?"
  EXPORTRATE: "str?"
  DAYRATESTART: "str?"
  NIGHTRATESTART: "str?"
  INFLUX_OUTPUT: bool
  INFLUX_URL: "str?"
  INFLUX_TOKEN: "str?"
  INFLUX_BUCKET: "str?"
  INFLUX_ORG: "str?"
  PYTHONPATH: str
  TZ: str
  WEB_DASH: bool
  WEB_DASH_PORT: int
  HOSTIP: str
  CACHELOCATION: "str?"
  DATASMOOTHER: "str?"
  SMARTTARGET: bool
  PALM_WINTER: "str"
  PALM_SHOULDER: "str"
  PALM_MIN_SOC_TARGET: int
  PALM_MAX_SOC_TARGET: int
  PALM_BATT_RESERVE: int
  PALM_BATT_UTILISATION: float
  PALM_WEIGHT: float
  GEAPI: "str?"
  SOLCASTAPI: "str?"
  SOLCASTSITEID: "str?"
  SOLCASTSITEID2: "str?"
  LOAD_HIST_WEIGHT: "str?"
